name: CI - Sistema de Ponto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
           python -m pip install -r requirements.txt

      - name: Rodar testes
        run: |
         PYTHONPATH=. python -m pytest --cov=src --cov=web --cov-report=term
