name: CI - Sistema de Ponto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          which python
          python --version
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest --cov=src --cov=web --cov-report=term
          